backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img

collections:
  - label: "carvalima"
    name: "Carvalima"
    folder: "content/carvalima"
    create: true
    fields:
      - {
          label: "description",
          name: "Descrição",
          widget: string,
          required: true,
        }
      - { label: "hasPlusSign", name: "Tem sinal de mais", widget: boolean }
      - {
          label: "number",
          name: "Numero",
          widget: number,
          value_type: "float",
          required: true,
        }
      - {
          label: "icon",
          name: "Icone",
          widget: image,
          allow_multiple: false,
          required: true,
        }
      - { label: "grandeza", name: "Ordem de grandeza", widget: string }
